version: '3'
services:

  postgres:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/laica
    ports:
      - '5432:5432'

volumes:
  postgres: